### ISSUE TITLE
DBFlute Engine: Sql2Entity procedure error on mysql-8.0.x and jdbc-8.0.x

### ISSUE THREAD

**Issue by jflute** [dbflute/dbflute-core#208]
// Japanese here

# Overview
DBFlute Engineで組み込んでるMySQLのJDBCドライバーは5.1.49だが、(extlibで)8.0.xに変えるとちょっと変なエラーが出てしまうようだ。

dbflute-test-dbms-mysql にて...

MySQL-5.7.13 + JDBC-8.0.33 => no problem
MySQL-5.7.13 + JDBC-8.4.0 => no problem
MySQL-8.0.36 + JDBC-8.0.33 => ArrayIndexOutOfBoundsException
MySQL-8.0.36 + JDBC-8.4.0 => ArrayIndexOutOfBoundsException

```
[df-sql2entity] 2024-07-24 22:22:14,763 INFO  -  -> All procedures are target: count=7
[df-sql2entity] 2024-07-24 22:22:14,777 INFO  - ...Calling: {call SP_IN_OUT_PARAMETER()}
[df-sql2entity] 2024-07-24 22:22:14,798 ERROR - Look! Read the message below.
[df-sql2entity] /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
[df-sql2entity] Failed to execute DBFlute Task 'Sql2Entity'.
[df-sql2entity] 
[df-sql2entity] [Advice]
[df-sql2entity] Check the exception messages and the stack traces.
[df-sql2entity] 
[df-sql2entity] [Database Product]
[df-sql2entity] MySQL 8.0.36
[df-sql2entity] 
[df-sql2entity] [JDBC Driver]
[df-sql2entity] MySQL Connector/J mysql-connector-j-8.0.33 (Revision: 7d6b0800528b6b25c68b52dc10d6c1c8429c100c) for JDBC 4.2
[df-sql2entity] * * * * * * * * * */
[df-sql2entity] java.lang.ArrayIndexOutOfBoundsException: 2
[df-sql2entity] 	at com.mysql.cj.jdbc.CallableStatement.setInOutParamsOnServer(CallableStatement.java:1985)
[df-sql2entity] 	at com.mysql.cj.jdbc.CallableStatement.execute(CallableStatement.java:844)
[df-sql2entity] 	at org.dbflute.logic.sql2entity.cmentity.DfProcedureExecutionMetaExtractor.doExtractExecutionMetaData(DfProcedureExecutionMetaExtractor.java:121)
[df-sql2entity] 	at org.dbflute.logic.sql2entity.cmentity.DfProcedureExecutionMetaExtractor.extractExecutionMetaData(DfProcedureExecutionMetaExtractor.java:90)
[df-sql2entity] 	at org.dbflute.logic.sql2entity.pmbean.DfProcedurePmbSetupper.getAvailableProcedureList(DfProcedurePmbSetupper.java:198)
[df-sql2entity] 	at org.dbflute.logic.sql2entity.pmbean.DfProcedurePmbSetupper.setupProcedure(DfProcedurePmbSetupper.java:92)
[df-sql2entity] 	at org.dbflute.task.DfSql2EntityTask.setupProcedure(DfSql2EntityTask.java:247)
...
```

**Comment by jflute** [comment]
# VenderMetaDataTest's procedure test
## MySQL-8.0.36 + JDBC-8.0.33
test_DatabaseMetaData_getProcedures_mainSchema():
```
maihamadb.null.SP_IN_OUT_PARAMETER, type=1
maihamadb.null.SP_NO_PARAMETER, type=1
maihamadb.null.SP_RETURN_RESULT_SET, type=1
maihamadb.null.SP_RETURN_RESULT_SET_MORE, type=1
maihamadb.null.SP_RETURN_RESULT_SET_WITH, type=1
maihamadb.null.SP_TRANSACTION_INHERIT, type=1
maihamadb.null.SP_VARIOUS_TYPE_PARAMETER, type=1
```

test_DatabaseMetaData_getProcedureColumns_mainSchema_basic():
```
[Procedure]
maihamadb.null.SP_IN_OUT_PARAMETER // SP_IN_OUT_PARAMETER
  v_in_varchar(1) VARCHAR(null, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
  v_out_varchar(4) VARCHAR(null, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
  v_inout_varchar(2) VARCHAR(null, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
maihamadb.null.SP_NO_PARAMETER // SP_NO_PARAMETER
maihamadb.null.SP_RETURN_RESULT_SET // SP_RETURN_RESULT_SET
maihamadb.null.SP_RETURN_RESULT_SET_MORE // SP_RETURN_RESULT_SET_MORE
maihamadb.null.SP_RETURN_RESULT_SET_WITH // SP_RETURN_RESULT_SET_WITH
  v_in_char(1) CHAR(null, 3, null) dataType=1 // SP_RETURN_RESULT_SET_WITH: null
  v_out_varchar(4) VARCHAR(null, 32, null) dataType=12 // SP_RETURN_RESULT_SET_WITH: null
  v_inout_varchar(2) VARCHAR(null, 32, null) dataType=12 // SP_RETURN_RESULT_SET_WITH: null
maihamadb.null.SP_TRANSACTION_INHERIT // SP_TRANSACTION_INHERIT
maihamadb.null.SP_VARIOUS_TYPE_PARAMETER // SP_VARIOUS_TYPE_PARAMETER
  v_in_varchar(1) VARCHAR(null, 32, null) dataType=12 // SP_VARIOUS_TYPE_PARAMETER: null
  v_out_varchar(4) VARCHAR(null, 32, null) dataType=12 // SP_VARIOUS_TYPE_PARAMETER: null
  v_out_char(4) CHAR(null, 3, null) dataType=1 // SP_VARIOUS_TYPE_PARAMETER: null
  v_in_text(1) TEXT(null, 65535, null) dataType=-1 // SP_VARIOUS_TYPE_PARAMETER: null
  v_out_text(4) TEXT(null, 65535, null) dataType=-1 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_in_numeric_integer(1) DECIMAL(5, 5, 0) dataType=3 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_in_numeric_bigint(1) DECIMAL(12, 12, 0) dataType=3 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_in_numeric_decimal(1) DECIMAL(5, 5, 3) dataType=3 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_out_decimal(4) DECIMAL(10, 10, 0) dataType=3 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_out_integer(4) INT(10, 10, 0) dataType=4 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_inout_integer(2) INT(10, 10, 0) dataType=4 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_out_bigint(4) BIGINT(19, 19, 0) dataType=-5 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_inout_bigint(2) BIGINT(19, 19, 0) dataType=-5 // SP_VARIOUS_TYPE_PARAMETER: null
  vvv_in_date(1) DATE(0, 10, null) dataType=91 // SP_VARIOUS_TYPE_PARAMETER: null
  vvv_out_datetime(4) DATETIME(0, 19, null) dataType=93 // SP_VARIOUS_TYPE_PARAMETER: null
...
```

## MySQL-8.0.36 + JDBC-5.1.49
test_DatabaseMetaData_getProcedures_mainSchema():
```
[Procedure]
maihamadb.null.SP_IN_OUT_PARAMETER, type=1
maihamadb.null.SP_NO_PARAMETER, type=1
maihamadb.null.SP_RETURN_RESULT_SET_MORE, type=1
maihamadb.null.SP_RETURN_RESULT_SET_WITH, type=1
maihamadb.null.SP_RETURN_RESULT_SET, type=1
maihamadb.null.SP_TRANSACTION_INHERIT, type=1
maihamadb.null.SP_VARIOUS_TYPE_PARAMETER, type=1
```

test_DatabaseMetaData_getProcedureColumns_mainSchema_basic():
```
[Procedure]
maihamadb.null.SP_IN_OUT_PARAMETER // SP_IN_OUT_PARAMETER
  v_in_varchar(1) VARCHAR(32, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
  v_out_varchar(4) VARCHAR(32, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
  v_inout_varchar(2) VARCHAR(32, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
maihamadb.null.SP_NO_PARAMETER // SP_NO_PARAMETER
maihamadb.null.SP_RETURN_RESULT_SET_MORE // SP_RETURN_RESULT_SET_MORE
maihamadb.null.SP_RETURN_RESULT_SET_WITH // SP_RETURN_RESULT_SET_WITH
  v_in_char(1) CHAR(3, 3, null) dataType=1 // SP_RETURN_RESULT_SET_WITH: null
  v_out_varchar(4) VARCHAR(32, 32, null) dataType=12 // SP_RETURN_RESULT_SET_WITH: null
  v_inout_varchar(2) VARCHAR(32, 32, null) dataType=12 // SP_RETURN_RESULT_SET_WITH: null
maihamadb.null.SP_RETURN_RESULT_SET // SP_RETURN_RESULT_SET
maihamadb.null.SP_TRANSACTION_INHERIT // SP_TRANSACTION_INHERIT
maihamadb.null.SP_VARIOUS_TYPE_PARAMETER // SP_VARIOUS_TYPE_PARAMETER
  v_in_varchar(1) VARCHAR(32, 32, null) dataType=12 // SP_VARIOUS_TYPE_PARAMETER: null
  v_out_varchar(4) VARCHAR(32, 32, null) dataType=12 // SP_VARIOUS_TYPE_PARAMETER: null
  v_out_char(4) CHAR(3, 3, null) dataType=1 // SP_VARIOUS_TYPE_PARAMETER: null
  v_in_text(1) TEXT(65535, 65535, null) dataType=-1 // SP_VARIOUS_TYPE_PARAMETER: null
  v_out_text(4) TEXT(65535, 65535, null) dataType=-1 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_in_numeric_integer(1) NUMERIC(5, 5, 0) dataType=3 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_in_numeric_bigint(1) NUMERIC(12, 12, 0) dataType=3 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_in_numeric_decimal(1) NUMERIC(5, 5, 3) dataType=3 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_out_decimal(4) DECIMAL(12, 12, null) dataType=3 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_out_integer(4) INTEGER(10, 10, 0) dataType=4 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_inout_integer(2) INTEGER(10, 10, 0) dataType=4 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_out_bigint(4) BIGINT(19, 19, 0) dataType=-5 // SP_VARIOUS_TYPE_PARAMETER: null
  vv_inout_bigint(2) BIGINT(19, 19, 0) dataType=-5 // SP_VARIOUS_TYPE_PARAMETER: null
  vvv_in_date(1) DATE(10, 10, null) dataType=91 // SP_VARIOUS_TYPE_PARAMETER: null
  vvv_out_datetime(4) DATETIME(19, 19, null) dataType=93 // SP_VARIOUS_TYPE_PARAMETER: null
```

## 分析
VenderMetaDataTestでJDBCのバージョンを差し替えて試してみると…
 
JDBC-8.0.x:
```
maihamadb.null.SP_IN_OUT_PARAMETER // SP_IN_OUT_PARAMETER
  v_in_varchar(1) VARCHAR(null, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
  v_out_varchar(4) VARCHAR(null, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
  v_inout_varchar(2) VARCHAR(null, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
```

JDBC-5.1.49:
```
maihamadb.null.SP_IN_OUT_PARAMETER // SP_IN_OUT_PARAMETER
  v_in_varchar(1) VARCHAR(32, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
  v_out_varchar(4) VARCHAR(32, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
  v_inout_varchar(2) VARCHAR(32, 32, null) dataType=12 // SP_IN_OUT_PARAMETER: null
```
なんか一個nullで取れなくなってるぞぅ。

ああでも、precision か。確かに最初テストが落ちて precision が取れなくなってるぞぅと思ったけど...
precision 取れないとダメなんじゃない？？？

いや、別に precision が取れなかったら、length を columnSize として採用するって感じでどっちか取れればいいから、この挙動の違いが今回のエラーにつながってるとは考えにくいな。

https://github.com/dbflute/dbflute-core/blob/develop/dbflute-engine/src/main/java/org/dbflute/logic/jdbc/metadata/basic/DfProcedureExtractor.java#L655

ぐぬぬぬ

**Comment by jflute** [comment]
# Sql2Entity log
## ログSQLの引数の数が違うぞぅ
8.0.33:
```
[df-sql2entity] 2024-07-24 22:22:14,763 INFO  -  -> All procedures are target: count=7
[df-sql2entity] 2024-07-24 22:22:14,777 INFO  - ...Calling: {call SP_IN_OUT_PARAMETER()}
```

5.1.49:
```
[df-sql2entity] 2024-07-24 22:48:15,973 INFO  -  -> All procedures are target: count=7
[df-sql2entity] 2024-07-24 22:48:15,986 INFO  - ...Calling: {call SP_IN_OUT_PARAMETER(?, ?, ?)}
```

試しに動いてる方のログを収集しようと思って見比べたら引数が違う。
でも、8.0.33でもVenderMetaDataTestでのplainなメタデータ取得では普通に引数情報は取れているのだが…

## 分析
SQL文字列の生成部分を追ってみる:
https://github.com/dbflute/dbflute-core/blob/develop/dbflute-engine/src/main/java/org/dbflute/logic/sql2entity/cmentity/DfProcedureExecutionMetaExtractor.java#L349

o 引数の?の数はargSizeで決まる
o argSizeはbindSizeで決まる
o bindSizeはprocedure.getBindParameterCount()
o getBindParameterCount()では _procedureColumnList で isBindParameter() のもの
```
for (DfProcedureColumnMeta columnInfo : _procedureColumnList) {
    if (columnInfo.isBindParameter()) {
        ++count;
    }
}
```

o isBindParameter()はほとんどtrueだが...
```
public boolean isBindParameter() {
    final DfProcedureColumnType columnType = _procedureColumnType;
    if (DfProcedureColumnType.procedureColumnResult.equals(columnType) // just in case
            || isSQLServerTableReturnValue()) { // pinpoint patch
        return false;
    }
    return true; // almost true

    // RESULT type does not have a column info basically
    // but sometimes it can be, so checks it just in case
}
```

o _procedureColumnList がないってありえるのか？

o うまくいってる 5.1.49 の方はもちょい前のログにこう出てる:
```
[df-sql2entity] 2024-07-24 22:48:15,966 INFO  - ...Reflecting source info to procedure meta: schema=maihamadb
[df-sql2entity] 2024-07-24 22:48:15,967 INFO  -   SP_IN_OUT_PARAMETER:{4, 86, cf957bfd}
```

o うまくいかない 8.0.33 の方でもメタデータ自体は取れてるがな:
```
[df-sql2entity] 2024-07-24 22:57:08,381 INFO  - ...Reflecting source info to procedure meta: schema=maihamadb
[df-sql2entity] 2024-07-24 22:57:08,381 INFO  -   SP_IN_OUT_PARAMETER:{4, 86, 6a92217b}
```

**Comment by jflute** [comment]
# DfProcedureExtractor
## カタログ名の修飾がある
とにもかくにも、ログの検証からなぜか引数の情報が取れていないことがわかった。
(VenderMetaDataTestでは取れてるのに、DfProcedureExtractorでは取れていないようで)

DfProcedureExtractorで引数情報を取得するところを追ってみた。

https://github.com/dbflute/dbflute-core/blob/develop/dbflute-engine/src/main/java/org/dbflute/logic/jdbc/metadata/basic/DfProcedureExtractor.java#L589
```
        if (isDatabaseMySQL() && Srl.is_NotNull_and_NotTrimmedEmpty(catalogName)) {
            // getProcedureColumns() of MySQL requires qualified procedure name when other catalog
            catalogArgName = catalogName;
            procedureArgName = Srl.connectPrefix(procedurePureName, catalogName, ".");
```

procedure名にcatalog名を付与している。
コメントでは、別catalog(別DB)のprocedureを取得するときは必須ということが書いてある。
ということで、ここをVenderMetaDataTestで検証してみた。

## VenderMetaDataTestでの検証

5.1.49 => catalog名をprocedure名に付与しても取得できる
8.0.33 => catalog名をprocedure名に付与すると取得できない

これだ。この違いだ。

5.1.49では同catalogについては付けても付けなくても取得できるので別catalogのために固定的に付与をしていたが、
8.0.33では少なくとも同catalogで付けると取得できなくなるので同catalogのときは付けてはいけないと言えそう。

でも、そもそも8.0.33で別catalogのとき大丈夫なのか？そこを検証しないといけなさそう。

**Comment by jflute** [comment]
ちなみに、JDBCを8.0.xにアップすると、メタデータが幾つか変わる。
まあ、致命的なものはないかな？？？

```
pp Entityにおいて
o DATETIME(19)がDATETIME(23)になる(ことがある?)
o YEARがYEAR(4)になる(ことがある?)
o BITがBIT(1)になる(ことがある?)
o VIEWはNotNull制約がすべて外れる

pp 外だしSQLにおいて
o INT(11)がINT(10)になる(ことがある?)
o BIGINT(20)がBIGINT(19)になる(ことがある?)

pp プロシージャーの引数の型において
o NUMERICがDECIMALになる(ことがある?)
o DECIMAL(12)がDECIMAL(10)になる(ことがある?)
o INTEGERがINTになる(ことがある?)
o DATE(10)がDATEになる(ことがある?)
o DATETIME(19)がDATETIMEになる(ことがある?)
```
